FROM node:20-bookworm-slim
WORKDIR /app
RUN apt-get update -y && apt-get install -y --no-install-recommends openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY package.json package-lock.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm ci && npm run db:generate
CMD ["npm", "run", "migrate:deploy", "-w", "@point/database"]
